export const AUTH_SERVICE = process.env.REACT_APP_AUTH_SERVICE_BASE_URL
export const CHARACTER_SERVICE = process.env.REACT_APP_CHARACTER_SERVICE_BASE_URL
export const GUILD_SERVICE = process.env.REACT_APP_GUILD_SERVICE_BASE_URL
export const EVENT_GROUPS_SERVICE = process.env.REACT_APP_EVENT_GROUPS_SERVICE_BASE_URL
